### ISSUE TITLE
Change the icon of the nav bar

### ISSUE THREAD

**Issue by Rishavagarwal12345** [Rishavagarwal12345/Hacktoberfest-2023#1]

**Comment by parag477** [comment]
I want to work on this issue. Can you please assign this to me

**Comment by Prasanthisandaka2005** [comment]
Hello Rishavagarwal12345

Myself Prasanthi Sandaka. I hope you're doing well.
I've recently started exploring open-source contributions, and I'm eager to learn and make a positive impact. While I'm new to this, I'm genuinely interested in your project and would love to get involved.

I couldn't find the website associated with the project, and I was hoping you could point me in the right direction. Once I have access to the website and more information about the project,  I'll dedicate myself to making valuable contributions.

Thank you for considering my interest, and I appreciate any guidance you can provide.

**Comment by Rishavagarwal12345** [comment]
> I want to work on this issue. Can you please assign this to me

I will start assigning issues once Hacktoberfest starts, which is from 1st Oct

**Comment by insanemindsk** [comment]
Hi Rishav ..I'm your subscriber loved your all informational videos ..thanks for always guiding us .
I want to work on this issue please assign this to me

**Comment by Sayandeep003** [comment]
Hi Rishav Gupta, came here after seeing your video. Love your content. I am staring out with open source contributions and wish to address this issue

**Comment by Prithiraj12345** [comment]
Heloo, Rishav I am interested in this project  please assign me in this.

**Comment by Priyagoyal786** [comment]
Hello Rishav ..I'm your subscriber loved your all informational videos and thanks for always guiding us .
I want to work on this issue please assign this to me and I'm thankful to you if you giving these opportunity

**Comment by divy15012005** [comment]
Hello Rishav bro 
It's a great initiative made by you to help us.
It would be great to work on this issue.

**Comment by suresh8919** [comment]
Hey @Rishavagarwal12345 can you Please assign this to me?

**Comment by dg2102** [comment]
Hey @Rishavagarwal12345  can you please assign this task to me? I would love to contribute to this project and get this opportunity.

**Comment by suresh8919** [comment]
Hello @Rishavagarwal12345 
It's a great initiative made by you to help us.
It would be great to work on this issue.
I hope you give me this opportunity to contribute

**Comment by Pyush-18** [comment]
Hello @Rishavagarwal12345 , I want to work on this issue ,please assign me this issue

**Comment by k7kaushal** [comment]
Hi @Rishavagarwal12345, 
I've been interested in working on open-source projects for quite a while now, Hacktoberfest seems to my starting point in this journey ahead, being new to open-source I feel your issue is a good first contribution for me to start with.
I would like the opportunity to contribute to this issue.

**Comment by Hackeries** [comment]
i want to work on this can you please assign this to me

**Comment by Harshkrsingh05** [comment]
hello Rishav , Nice to hear that you are helping us to get a pull request, add me also

**Comment by Chandan-Singh10** [comment]
I want to work on this issues please assign me this issues as soon as possible.

**Comment by MohammedFaisal02** [comment]
Hello @Rishavagarwal12345 can you please assign this to me as I'm eager to work on this

**Comment by yashwanthvarma18** [comment]
Hello @Rishavagarwal12345  , I'm eager to contribute. Please assign me

**Comment by ayush1108g** [comment]
Hello, Rishav I am interested in this project please assign me in this. I'm eager to contribute.

**Comment by HarshithAlfred** [comment]
Is this code run on node or yarn and where can I find the original web link of this code

**Comment by inbuilt-aura** [comment]
Hello, well there are a lot of requests yet if you need,plzz assign the issue to me.I would love to contribute.

**Comment by Kajal2468** [comment]
I want to work on this issue in Hacktoberfest'23

Thank You!!

**Comment by Saroj-pradhan** [comment]
> > I want to work on this issue. Can you please assign this to me
> 
> I will start assigning issues once Hacktoberfest starts, which is from 1st Oct

if you assign the issue to one person, so only 10-15  pepole select in  hacktoberfest , please reply and clear all doubt of audiance . i think you said that each pull request of any one will accepted.

**Comment by praptisharma28** [comment]
HEY @Rishavagarwal12345 , you can assign me this issue, I will happily contrivute. You can check my page too for the contributions I did.

**Comment by Aapush01** [comment]
Almost work is done can you assign me so I can show you.

**Comment by satyamkumar46** [comment]
i'm interested to work in this issue plz assign me

**Comment by sheelganvir** [comment]
Hello Rishav! I want to work on this issue please assign this to me
