### ISSUE TITLE
To be add social media links in footer.

### ISSUE THREAD

**Issue by Prasad-mutnale** [Rishavagarwal12345/Hacktoberfest-2023#10]

**Comment by Chandan-Singh10** [comment]
I want to work on this issues please assign me this issues as soon as possible.

**Comment by Nikhil743** [comment]
Hello @Prasad-mutnale ,
Please assign this project to me.

**Comment by imSanko** [comment]
I can help you get the social media link in the  footer part can you assign the task to me ! @Prasad-mutnale

**Comment by Krish3914** [comment]
I will work and solve this issue in your desired and efficient manner.

**Comment by Priyagoyal786** [comment]
I want to work on these issue assign these as soon as possible.

**Comment by AshishPandey26** [comment]
I can get this issue solved assign this to me

**Comment by parthgithubrit** [comment]
Hello sir, Can you assign this issue to me?

**Comment by bhavy03** [comment]
hi @Prasad-mutnale i would like to work on this issue

**Comment by shishirkj** [comment]
hi if not assigned can i work on this issue?

**Comment by VishalAggarwal2** [comment]
I Want To Resolve  This Issue

**Comment by Ashima2003** [comment]
I want to work on this issue kindly assign me this

**Comment by suresh8919** [comment]
Hey @Rishavagarwal12345  Can you please assign me this.

**Comment by vedantterse** [comment]
@Rishavagarwal12345  hey there, hope you are doing good, saw this good first issue , looks perfect for the start of my journey towards open source.. looking forward to get to work on the issue , have an unique solution to it

**Comment by nooralamf42** [comment]
wtf is wrong with your code ?? do you even know what is react and how it works?? 
the code you given is fvcking trash 
there is no app.js file and you made bunch of useless files 
![image](https://github.com/Rishavagarwal12345/Hacktoberfest-2023/assets/90553481/25d58a3d-a98f-4d99-a62a-b5df9fa4792d)
![image](https://github.com/Rishavagarwal12345/Hacktoberfest-2023/assets/90553481/d244c4d6-d35a-48e8-81b9-29915847c959)

**Comment by Mayankaharma2003** [comment]
I want to work on this issues please assign me this issues as soon as possible.

**Comment by Mayankaharma2003** [comment]
I want to work on this issues please assign me this issues as soon as possible. plese give this one to me

**Comment by ManeetChhabra** [comment]
plz assign this issue to me

**Comment by Prasad-mutnale** [comment]
Hello @Rishavagarwal12345 i solved this issue would you please assign me this issue.

**Comment by Prasad-mutnale** [comment]
Hello @Rishavagarwal12345  i solved this issue would you please assign me this issue.

**Comment by vedantterse** [comment]
hey there @Rishavagarwal12345, hope you are doing well, saw this good first issue, looks perfect for the start of my journey towards open source I am looking forward to getting to work on the topic, and have a unique solution to it

**Comment by Rohan-Maruti** [comment]
I can help you get the social media link in the footer part can you assign the work to me ! @Prasad-mutnale

**Comment by shadabdln** [comment]
I am more than capable of assisting you in adding the social media link to the footer section. By assigning this task to me, you can rest assured that it will be completed efficiently and seamlessly.

**Comment by Kajal2468** [comment]
I want to work on this issue plz assign

thanks

**Comment by hollermay** [comment]
Hello Sir, can you assign this issue to me?

**Comment by Savi-07** [comment]
Hello @Rishavagarwal12345 if this issue is still open can I work on this from 1st of Oct as this it seems to be a first-good-issue

**Comment by Tahasildarrashid** [comment]
Hello @Rishavagarwal12345 I am a beginner and I am excited about the hacktober fest so can you please assign me this issue and allow me to do my first pull request successfully!!!

**Comment by praptisharma28** [comment]
HEY @Rishavagarwal12345 , you can assign me this issue,I know REact, Django. It's easy for me to add a footer. You can check my page too for the contributions I did.

**Comment by ayusharma-20** [comment]
Hi Rishav

I hope this message finds you well. I came across issue of adding social media links in the footer. After reviewing it, I'm keen on taking this up and working towards a solution. Given my background in **HTML,CSS & JS**, I believe I can make a meaningful contribution to this task. Would it be possible to have this issue assigned to me?

I truly appreciate your time and consideration. Thank you for the opportunity to contribute to the project.

Looking forward to your response.

**Comment by ParvGautam** [comment]
I want to work on in this issue please assign me this issue.

**Comment by satyamkumar46** [comment]
i'm interested to work in this issue plz assign me

**Comment by parasvekariya26** [comment]
plz assign to me

**Comment by insanemindsk** [comment]
Hello @Rishavagarwal12345 i solved this issue would you please assign me this issue.

**Comment by Mayankaharma2003** [comment]
ok you can work on that 👍
