### ISSUE TITLE
Feature: Improving design of the Footer

### ISSUE THREAD

**Issue by SAGARSINGH-1** [Rishavagarwal12345/Hacktoberfest-2023#104]
Implementing New Features and Resolving Bugs in the Website Footer Design

**Comment by SAGARSINGH-1** [comment]
<img width="946" alt="image" src="https://github.com/Rishavagarwal12345/Hacktoberfest-2023/assets/81561733/b7e883ff-4ce4-4075-86cc-a29ba92f3a28">

This is the updated Footer

**Comment by antriksh-9** [comment]
Hey @Rishavagarwal12345 I want to work on this issue. 
Can you please assign it to me?

**Comment by omborate100** [comment]
Hey @Rishavagarwal12345 , can you assign me this task?
