### ISSUE TITLE
#Bug - Empty Field Messages Allowed

### ISSUE THREAD

**Issue by himanshu181749** [Rishavagarwal12345/Hacktoberfest-2023#111]
Bug Summary:
Currently, the application allows empty field messages to be submitted without any validation or error handling. This poses a usability issue and may lead to incomplete or ambiguous data being submitted, affecting the overall functionality and user experience of the application.

https://github.com/Rishavagarwal12345/Hacktoberfest-2023/assets/75875283/75c3dc9d-73bc-435d-b07d-c26604567d03

**Comment by SAGARSINGH-1** [comment]
please assign this issue to me

**Comment by himanshu181749** [comment]
@Rishavagarwal12345  I've already created a PR for the same....please review and let me know if there is anything i can help with.
