### ISSUE TITLE
ProjectCard should be in a separate file as a component, which is currently in Works.jsx file.

### ISSUE THREAD

**Issue by noorali180** [Rishavagarwal12345/Hacktoberfest-2023#129]
I can fix this kindly assign it to me.

**Comment by noorali180** [comment]
@Rishavagarwal12345  I have opened a PR, kindly review and merge it.

**Comment by AshwinSriram11** [comment]
@Rishavagarwal12345 I have made the changes requires for this issue. Kindly review my PR. Thank you.
