### ISSUE TITLE
Readme file git create branch instruction issue

### ISSUE THREAD

**Issue by Pankaj-Bind** [Rishavagarwal12345/Hacktoberfest-2023#14]
in readme file it is not given how to create branch it is given how to checkout branch

**Comment by Pankaj-Bind** [comment]
I would like to solve this issue, will you assign me this work.

**Comment by vedantterse** [comment]
this issue is geniune and i guess I can solve it. it would be great if you could assign me this!!

**Comment by HarshithAlfred** [comment]
Hey @Pankaj-Bind I guess you have mistaken , checkout means to create a branch 
I think this might solve your doubt

**Comment by Haris-Mohanty** [comment]
The command git checkout -b my-branch both creates and checks out (switches to) a new branch named "my-branch." So, in essence, it accomplishes both tasks at once. So I think it should not be change.

**Comment by Pankaj-Bind** [comment]
thanks for assigning me this work

**Comment by Pankaj-Bind** [comment]
i'd made pull request would you lable it hactoberfest-accepted

**Comment by ashfaque-mustaque** [comment]
Assign me I will do

**Comment by praptisharma28** [comment]
HEY @Rishavagarwal12345 , you can assign me this issue, I have done complete study on gitbash and git commands, You can check my page too for the contributions I did. I can add the commands. Happy to contribute.

**Comment by suresh33661** [comment]
Assign me

**Comment by VBPMP** [comment]
Assign me

**Comment by aditya-0786** [comment]
Hello Rishav bhaiya. I am 1st year student of b.tech from tier 3 college. So this competition is very important for my future. And I want to prove myself infront of everyone. So please can you assign this project to me. It would be great help for me🙏🙏.
