### ISSUE TITLE
add bird animation using html/css

### ISSUE THREAD

**Issue by Wendell00** [Rishavagarwal12345/Hacktoberfest-2023#196]
![Sem título](https://github.com/Rishavagarwal12345/Hacktoberfest-2023/assets/62032363/d9cc3d31-5275-4046-9d2d-89899909e929)

**Comment by chakrabortysukalyan** [comment]
@Rishavagarwal12345, I would like to work on this issue, please assign me this issue
Also this is my first hacktoberfest and your videos really guided me well, thanks.

**Comment by parthivghose2919** [comment]
@Rishavagarwal12345, sir I would like to work on this issue, please assign me this issue..Thank you!!!

**Comment by Hiteshbemal24** [comment]
@Rishavagarwal12345 I want to work on this issue , assign me please .

**Comment by aarth01** [comment]
hello please assign this to me it will really  helpful for me as well as i will make a good designed  animation of bird
