### ISSUE TITLE
Change the 3D PC image

### ISSUE THREAD

**Issue by Rishavagarwal12345** [Rishavagarwal12345/Hacktoberfest-2023#2]

**Comment by yr1404** [comment]
What do you want to change it to?

**Comment by suresh8919** [comment]
Hello @Rishavagarwal12345 I'm started working on this Please assign me this

**Comment by Prithiraj12345** [comment]
I am interested, please provide the details what to do thanks you.

**Comment by divy15012005** [comment]
Hello Rishav bro 
It's a great initiative made by you to help us.
It would be great to work on this issue.

**Comment by Chandan-Singh10** [comment]
I want to work on this issues please assign me this issues as soon as possible.

**Comment by suresh8919** [comment]
Hey @Rishavagarwal12345 I want to contribute to this issues please assign me this.

**Comment by MohammedFaisal02** [comment]
Hello @Rishavagarwal12345 can you please assign this to me as I'm eager to work on this

**Comment by yashwanthvarma18** [comment]
Hello @Rishavagarwal12345  , I'm eager to contribute. Please assign me

**Comment by VishalAggarwal2** [comment]
Hello I want to contribute in this given issue

**Comment by sahilbhise09** [comment]
can you please assign it to me ?

**Comment by sheelganvir** [comment]
Hello Rishav! I want to work on this issue please assign it to me

**Comment by VBPMP** [comment]
Can you Please Assign it to me

**Comment by Harshjha15** [comment]
body {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  margin: 0;
  background-color: #f0f0f0;
}

.card-container {
  perspective: 1000px;
}

.card {
  position: relative;
  width: 200px;
  height: 300px;
  transform-style: preserve-3d;
  transition: transform 0.6s;
}

.card:hover {
  transform: rotateY(180deg);
}

.front, .back {
  position: absolute;
  width: 100%;
  height: 100%;
  backface-visibility: hidden;
}

.front {
  background-color: #3498db;
  color: white;
}

.back {
  background-color: #e74c3c;
  color: white;
  transform: rotateY(180deg);
}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="styles.css">
  <title>3D Card with Hover Effect</title>
</head>
<body>
  <div class="card-container">
    <div class="card">
      <div class="front">Front</div>
      <div class="back">Back</div>
    </div>
  </div>
</body>
</html>

**Comment by Harshjha15** [comment]
// HTML
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="styles.css">
  <title>3D Card with Hover Effect</title>
</head>
<body>
  <div class="card-container">
    <div class="card">
      <div class="front">Front</div>
      <div class="back">Back</div>
    </div>
  </div>
</body>
</html>

// CSS

body {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  margin: 0;
  background-color: #f0f0f0;
}

.card-container {
  perspective: 1000px;
}

.card {
  position: relative;
  width: 200px;
  height: 300px;
  transform-style: preserve-3d;
  transition: transform 0.6s;
}

.card:hover {
  transform: rotateY(180deg);
}

.front, .back {
  position: absolute;
  width: 100%;
  height: 100%;
  backface-visibility: hidden;
}

.front {
  background-color: #3498db;
  color: white;
}

.back {
  background-color: #e74c3c;
  color: white;
  transform: rotateY(180deg);
}

**Comment by aditya-0786** [comment]
Hello Rishav bhaiya. I am 1st year student of b.tech from tier 3 college. So this competition is very important for my future. And I want to prove myself infront of everyone. So please can you assign this project to me. It would be great help for me🙏🙏.

**Comment by kartik9977** [comment]
Hello, @Rishavagarwal12345, Can you please assign it to me.

**Comment by Tayybar-Rahman-Khan** [comment]
I want to work on this issue  @Rishavagarwal12345 please assign me this issue as soon as possible.

**Comment by Aditya5556** [comment]
Hey brother, @Rishavagarwal12345 please assign mw this issue

**Comment by angananana** [comment]
hii @Rishavagarwal12345 it'ld be my first contribution could you please assign it to me

**Comment by Abdullahkhanspn** [comment]
hey rishav bro please assign this issue to me i am a Android Developer and Participated first time @Rishavagarwal12345
