### ISSUE TITLE
"App.jsx" file missing in the Default branch (Master)

### ISSUE THREAD

**Issue by parveshsaini** [Rishavagarwal12345/Hacktoberfest-2023#27]
I couldn't run the project due to absence of App.jsx

<img width="648" alt="image" src="https://github.com/Rishavagarwal12345/Hacktoberfest-2023/assets/97528080/f331b66d-a4c5-40bb-a588-e2ec7558edff">

<img width="356" alt="image" src="https://github.com/Rishavagarwal12345/Hacktoberfest-2023/assets/97528080/9e955824-d5b1-4ff8-88dc-4f52131498ea">

**Comment by Haris-Mohanty** [comment]
Could you please assign this issue to me so that I can get started on it?
