### ISSUE TITLE
Creating pic animation while hovering on it

### ISSUE THREAD

**Issue by Pyush-18** [Rishavagarwal12345/Hacktoberfest-2023#5]

**Comment by Chandan-Singh10** [comment]
I want to work on this issues please assign me this issues as soon as possible.

**Comment by Vaishali785** [comment]
Hi @Pyush-18 @Rishavagarwal12345 I'd like to work on this. Could you please describe what type of animation do you want?

**Comment by Surv2308** [comment]
Hi @Rishavagarwal12345 I'd like to work on this ,could you please describe what kind of animation you want?

**Comment by Muskan020** [comment]
First, construct an HTML structure that includes an <img> element to display the image you want to animate. Then, utilize CSS to define the specific hover animations you desire. To facilitate this, create a container for the image using CSS, making sure to apply relevant styles. Next, employ the: hover pseudo-class in your CSS to target the image when users hover over it, thus triggering the intended hover effects. Lastly, fine-tune the transition properties within your CSS to ensure the animations are smooth and visually appealing. 
I will follow above approach to solve this issue. I request you to assign this issue to me.

**Comment by MohammedFaisal02** [comment]
Hello @Rishavagarwal12345 can you please assign this to me as I'm eager to work on this

**Comment by suresh8919** [comment]
Hi @Rishavagarwal12345 I want to work on this can you please assign me this

**Comment by yashwanthvarma18** [comment]
Hello @Rishavagarwal12345  , I'm eager to contribute. Please assign me

**Comment by Ratikant-rout** [comment]
Hello Brother Can You Please Assing Me This Project?

**Comment by saku1331** [comment]
I want to work on this issue. Kindly assign this me.

**Comment by Kritikajain6104** [comment]
i want to work on it please assign it to me.

**Comment by ParvGautam** [comment]
I want to work on this issue Please Assign me this Issue

**Comment by Rasayan** [comment]
Hey @Pyush-18 , I believe I could make some pretty good picture animations, please assign me this issue.

**Comment by insanemindsk** [comment]
Hello @Rishavagarwal12345 i solved this issue would you please assign me this issue.
