### ISSUE TITLE
Adding a Login-page File

### ISSUE THREAD

**Issue by zhackerloopback** [Rishavagarwal12345/Hacktoberfest-2023#80]
Add a Login-page using HTML And CSS

**Comment by Tomkndn** [comment]
It should be renered on App.jsx or we have to just create a file?

**Comment by kartik9977** [comment]
Hey, Can you please assign me this task

**Comment by EniolaAdemola** [comment]
Hi, Kindly assign me to this task, i have experience in this field.

**Comment by EniolaAdemola** [comment]
!assign

**Comment by trapti77** [comment]
Add login page using html and css. 
Here is the screenshot of login page
![Screenshot (97)](https://github.com/Rishavagarwal12345/Hacktoberfest-2023/assets/114275270/05a7ec80-7e19-4484-b673-ff180c2fb301)

**Comment by trapti77** [comment]
please sir adding my login-page

**Comment by Vighnesh-3** [comment]
Can you assign me this task. Iam sending an attachment of the preview
<img width="717" alt="login_git" src="https://github.com/Rishavagarwal12345/Hacktoberfest-2023/assets/113260053/02c0b017-ab80-4075-9d40-5b4080a09598">
