### ISSUE TITLE
ADD

### ISSUE THREAD

**Issue by azabadaudiya** [Rishavagarwal12345/Hacktoberfest-2023#94]
should i add calculator i have created using .net?

**Comment by Vansh16aug** [comment]
hey bro tell me what to do i ll do , so pls assign it to me

**Comment by praptisharma28** [comment]
Assign this to me, I would like to contribute.

**Comment by azabadaudiya** [comment]
assigned me i will upload

**Comment by sid346184** [comment]
I added a stopwatch please merge

**Comment by praptisharma28** [comment]
Thankyou for assigning me @Rishavagarwal12345 . I have made a PR and added a webpage in the folder (FindAPic) , hope you like it. I want to contribute to Hacktoberfest and want my PRs to merge. Will be happy if you merge this one. Thankyou for reading. Good-day!

**Comment by RealCifer** [comment]
Hello @Rishavagarwal12345 hope you are doing well. I want to contribute to this issue. Please assign me. And also provide some additional information regarding this issue

**Comment by Abdullahkhanspn** [comment]
hey @Rishavagarwal12345 please assign me this i will add my Android Apps in this .
